# SPDX-License-Identifier: Apache-2.0

from typing import Optional

class fgds_file_handle:
    def __init__(self, filename: str, o_direct: bool, device_id: int): ...
    def get_device_id(self) -> int: ...
    def get_fd(self) -> int: ...

class fgds_device_buffer:
    def __init__(self, dev_ptr: int, length: int): ...
    def get_base_address(self) -> int: ...
    def get_length(self) -> int: ...

class fgds_file_reader:
    def __init__(self, max_threads: int, device_id: int): ...
    def submit_read(
        self,
        fh: fgds_file_handle,
        dst: fgds_device_buffer,
        offset: int,
        length: int,
        ptr_off: int,
    ) -> int: ...
    def wait_read(self, id: int) -> int: ...

def fgds_open(device_id: int) -> int: ...
def fgds_close(device_id: int) -> int: ...
def fgds_regmem(
    device_id: int, addr: int, size: int, target_addr: Optional[int]
) -> int: ...
def fgds_deregmem(device_id: int, addr: int, size: int) -> int: ...
def fgds_read(
    fd: int, device_id: int, buf: int, length: int, offset: int, ptr_off: int
) -> int: ...
def fgds_load_library() -> None: ...
def fgds_close_library() -> None: ...
def fgds_is_initialized() -> bool: ...
